version: '3.4'

services:
  hbtsteam01speechtocode:
    image: hbtsteam01speechtocode
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c 
      "python ./test.py
      && tail -f /dev/null"

# tail -f /dev/null